services:
  - type: web
    name: deepseek-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PORT
        value: 10000
